/**
 * 命理角色轉譯模組 - 完整角色數據
 * 包含天干主將、地支軍師的完整 Buff/Debuff 定義
 */

import type { GanCharacter, ZhiCharacter, WuxingElement } from './types';

// ==================== 天干主將（十位）====================

export const GAN_CHARACTERS: Record<string, GanCharacter> = {
  甲: {
    id: '甲',
    gan: '甲',
    title: '森林將軍',
    description: '威武雄壯的森林守護者，如參天大樹般屹立不搖，擁有強大的生命力和開創領導能力',
    element: '木',
    yinYang: '陽',
    color: '#228B22',
    position: 'general',
    archetypes: ['創世族長', '開拓先鋒', '森林之王'],
    buff: '開疆闢土，規劃長遠，領導氣場強大',
    buffValue: 25,
    debuff: '固執己見，不知變通，剛愎自用',
    debuffValue: -15,
    personality: ['剛強', '進取', '領導', '正直'],
    actionStyle: '直衝突破，勇往直前',
    storyKeywords: ['開創', '領導', '堅毅', '成長'],
    scenarioTemplate: '以{title}之姿，率領軍團開闢新局，其{buff}，然亦需慎防{debuff}之傾向。'
  },
  乙: {
    id: '乙',
    gan: '乙',
    title: '花蔓軍師',
    description: '溫柔而富有智慧的植物智者，如藤蔓般柔韌，善於策略與協調，以柔克剛',
    element: '木',
    yinYang: '陰',
    color: '#90EE90',
    position: 'general',
    archetypes: ['謀略長老', '柔術大師', '和平使者'],
    buff: '柔韌適應，深謀遠慮，善於協調各方',
    buffValue: 20,
    debuff: '過於依附，缺乏主見，優柔寡斷',
    debuffValue: -12,
    personality: ['柔順', '智慧', '協調', '適應'],
    actionStyle: '迂迴婉轉，以柔克剛',
    storyKeywords: ['協調', '柔韌', '智謀', '適應'],
    scenarioTemplate: '{title}以柔軟身段穿梭戰局，{buff}為其優勢，然須警惕{debuff}之弱點。'
  },
  丙: {
    id: '丙',
    gan: '丙',
    title: '烈日戰神',
    description: '熾熱如太陽的戰士，光芒萬丈，帶來光明與能量，激發全軍士氣',
    element: '火',
    yinYang: '陽',
    color: '#FF4500',
    position: 'general',
    archetypes: ['太陽神將', '光明使者', '熱血統帥'],
    buff: '光明磊落，激發士氣，感染力極強',
    buffValue: 28,
    debuff: '過於張揚，易燃易盡，缺乏持久力',
    debuffValue: -18,
    personality: ['熱情', '光明', '積極', '慷慨'],
    actionStyle: '光明正大，氣勢磅礴',
    storyKeywords: ['光明', '熱情', '激勵', '輝煌'],
    scenarioTemplate: '{title}如日中天，其{buff}振奮全軍，然{debuff}亦為隱患。'
  },
  丁: {
    id: '丁',
    gan: '丁',
    title: '誓燈法師',
    description: '溫暖的火焰魔法師，如燭火般穩定而持久，在黑暗中指引方向',
    element: '火',
    yinYang: '陰',
    color: '#FF6347',
    position: 'general',
    archetypes: ['燭光導師', '溫煦族母', '智焰祭司'],
    buff: '溫和持久，洞察入微，照亮他人',
    buffValue: 22,
    debuff: '過於敏感，容易消耗，心思過重',
    debuffValue: -12,
    personality: ['溫和', '持續', '深邃', '細膩'],
    actionStyle: '持續燃燒，默默照亮',
    storyKeywords: ['溫暖', '智慧', '持久', '引導'],
    scenarioTemplate: '{title}以穩定火光照耀全軍，{buff}為其特色，惟需留意{debuff}。'
  },
  戊: {
    id: '戊',
    gan: '戊',
    title: '山岳守護',
    description: '穩如泰山的大地守護者，堅實可靠，提供最堅實的防護與後盾',
    element: '土',
    yinYang: '陽',
    color: '#8B4513',
    position: 'general',
    archetypes: ['山嶽巨人', '大地之盾', '堡壘統帥'],
    buff: '穩重可靠，防禦堅固，承載力強',
    buffValue: 24,
    debuff: '行動遲緩，過於保守，抗拒改變',
    debuffValue: -14,
    personality: ['穩重', '可靠', '守護', '包容'],
    actionStyle: '穩紮穩打，固若金湯',
    storyKeywords: ['穩固', '守護', '承載', '厚重'],
    scenarioTemplate: '{title}如山嶽般穩固，以{buff}護衛全軍，但{debuff}或成阻礙。'
  },
  己: {
    id: '己',
    gan: '己',
    title: '大地母親',
    description: '慈愛的大地女神，孕育萬物的溫柔力量，滋養並調和團隊',
    element: '土',
    yinYang: '陰',
    color: '#DEB887',
    position: 'general',
    archetypes: ['田園守護', '豐收女神', '調和聖者'],
    buff: '包容養育，調和矛盾，滋養萬物',
    buffValue: 20,
    debuff: '過於遷就，缺乏原則，容易被利用',
    debuffValue: -10,
    personality: ['慈愛', '包容', '養育', '調和'],
    actionStyle: '潤物無聲，以柔養剛',
    storyKeywords: ['養育', '包容', '調和', '滋潤'],
    scenarioTemplate: '{title}以母性力量滋養軍團，{buff}深得人心，然{debuff}需加警惕。'
  },
  庚: {
    id: '庚',
    gan: '庚',
    title: '天鍛騎士',
    description: '堅硬如鋼的戰士，擁有銳利的攻擊力和決斷力，正義凜然',
    element: '金',
    yinYang: '陽',
    color: '#C0C0C0',
    position: 'general',
    archetypes: ['鋼鐵教官', '斬鋒將軍', '正義執行'],
    buff: '決斷果敢，執行力強，紀律嚴明',
    buffValue: 26,
    debuff: '過於嚴苛，不近人情，剛硬易折',
    debuffValue: -16,
    personality: ['堅毅', '鋒利', '正義', '果斷'],
    actionStyle: '雷厲風行，一擊必中',
    storyKeywords: ['決斷', '正義', '鋒銳', '執行'],
    scenarioTemplate: '{title}以鐵血手腕統御全軍，{buff}令敵膽寒，惟{debuff}亦為雙刃。'
  },
  辛: {
    id: '辛',
    gan: '辛',
    title: '靈晶鑑定師',
    description: '精緻優雅的金屬工藝師，追求完美與美感，洞察細節之美',
    element: '金',
    yinYang: '陰',
    color: '#FFD700',
    position: 'general',
    archetypes: ['珠寶大師', '精緻劍客', '美學導師'],
    buff: '追求完美，洞察細節，品味高雅',
    buffValue: 20,
    debuff: '過於挑剔，吹毛求疵，心胸狹隘',
    debuffValue: -12,
    personality: ['精緻', '優雅', '追求美', '敏感'],
    actionStyle: '精準細膩，以巧勝拙',
    storyKeywords: ['精緻', '完美', '美感', '洞察'],
    scenarioTemplate: '{title}以精湛技藝服眾，{buff}令人讚嘆，然{debuff}有時反成桎梏。'
  },
  壬: {
    id: '壬',
    gan: '壬',
    title: '龍河船長',
    description: '奔騰不息的水流領袖，智慧如海洋般深邃，能屈能伸，包容萬象',
    element: '水',
    yinYang: '陽',
    color: '#4169E1',
    position: 'general',
    archetypes: ['海洋霸主', '潮汐統帥', '智海艦長'],
    buff: '智慧深邃，包容萬象，適應力強',
    buffValue: 24,
    debuff: '漂泊不定，缺乏根基，過於飄忽',
    debuffValue: -14,
    personality: ['流動', '智慧', '變化', '包容'],
    actionStyle: '順勢而為，以柔制剛',
    storyKeywords: ['智慧', '包容', '流動', '深邃'],
    scenarioTemplate: '{title}如洪水之勢席捲戰場，{buff}難以抵擋，但{debuff}亦需謹慎。'
  },
  癸: {
    id: '癸',
    gan: '癸',
    title: '甘露天使',
    description: '溫柔如甘露的水靈，滋潤萬物的純淨力量，細膩敏感，洞察人心',
    element: '水',
    yinYang: '陰',
    color: '#87CEEB',
    position: 'general',
    archetypes: ['甘露醫師', '夢境守護', '靈泉祭司'],
    buff: '滋養細膩，洞察人心，療癒撫慰',
    buffValue: 20,
    debuff: '多愁善感，優柔寡斷，容易消沉',
    debuffValue: -12,
    personality: ['純淨', '滋潤', '細膩', '敏感'],
    actionStyle: '潤物無聲，滲透人心',
    storyKeywords: ['滋潤', '療癒', '純淨', '細膩'],
    scenarioTemplate: '{title}以甘露滋潤軍心，{buff}凝聚士氣，然{debuff}或影響決策。'
  }
};

// ==================== 地支軍師（十二位）====================

export const ZHI_CHARACTERS: Record<string, ZhiCharacter> = {
  子: {
    id: '子',
    zhi: '子',
    title: '夜行刺客',
    description: '隱藏在夜色中的水系刺客，行動迅速而神秘，在暗處掌控全局',
    element: '水',
    yinYang: '陽',
    color: '#191970',
    position: 'strategist',
    archetypes: ['暗影密探', '夜間統帥', '情報首領'],
    buff: '潛伏突襲，情報蒐集，暗中佈局',
    buffValue: 22,
    debuff: '過於陰沉，缺乏信任，疑心過重',
    debuffValue: -14,
    personality: ['機敏', '隱秘', '果斷', '敏銳'],
    actionStyle: '暗中潛行，一擊致命',
    storyKeywords: ['隱秘', '智謀', '夜行', '突襲'],
    scenarioTemplate: '{title}於暗夜中運籌帷幄，{buff}令敵措手不及，然{debuff}或致孤立。',
    timePeriod: '23:00-01:00',
    season: '冬季',
    hiddenStems: ['癸']
  },
  丑: {
    id: '丑',
    zhi: '丑',
    title: '封藏守衛',
    description: '忠誠可靠的土系守衛，默默守護重要事物，耐心等待時機',
    element: '土',
    yinYang: '陰',
    color: '#8B4513',
    position: 'strategist',
    archetypes: ['寶庫守護', '耐心長老', '封印大師'],
    buff: '穩固守護，資源儲備，耐心等待',
    buffValue: 20,
    debuff: '過於保守，錯失時機，固守成規',
    debuffValue: -12,
    personality: ['忠誠', '可靠', '耐心', '穩固'],
    actionStyle: '守株待兔，穩中求勝',
    storyKeywords: ['守護', '儲備', '耐心', '穩固'],
    scenarioTemplate: '{title}默默守護軍團資源，{buff}確保後勤無虞，但{debuff}或失先機。',
    timePeriod: '01:00-03:00',
    season: '冬季',
    hiddenStems: ['己', '癸', '辛']
  },
  寅: {
    id: '寅',
    zhi: '寅',
    title: '雷虎獵人',
    description: '勇猛的木系獵人，在森林中展現王者風範，開創先鋒',
    element: '木',
    yinYang: '陽',
    color: '#228B22',
    position: 'strategist',
    archetypes: ['森林獵人', '先鋒猛將', '虎嘯將軍'],
    buff: '先鋒衝陣，開創局面，勇猛無畏',
    buffValue: 24,
    debuff: '行事草率，過於衝動，獨斷專行',
    debuffValue: -14,
    personality: ['勇猛', '直率', '威嚴', '開創'],
    actionStyle: '虎躍龍騰，一馬當先',
    storyKeywords: ['開創', '勇猛', '先鋒', '威嚴'],
    scenarioTemplate: '{title}衝鋒在前開闢戰場，{buff}振奮士氣，然{debuff}需有人勸阻。',
    timePeriod: '03:00-05:00',
    season: '春季',
    hiddenStems: ['甲', '丙', '戊']
  },
  卯: {
    id: '卯',
    zhi: '卯',
    title: '玉兔使者',
    description: '靈巧的木系使者，帶來春天的生機與希望，溫和而充滿活力',
    element: '木',
    yinYang: '陰',
    color: '#32CD32',
    position: 'strategist',
    archetypes: ['和平使者', '春風信使', '生機導師'],
    buff: '靈活應變，和平斡旋，生機勃勃',
    buffValue: 18,
    debuff: '過於軟弱，缺乏決斷，容易退縮',
    debuffValue: -10,
    personality: ['靈巧', '溫和', '有活力', '協調'],
    actionStyle: '靈活跳躍，隨機應變',
    storyKeywords: ['和平', '生機', '靈巧', '協調'],
    scenarioTemplate: '{title}以和平手段斡旋各方，{buff}化解衝突，但{debuff}有時顯得軟弱。',
    timePeriod: '05:00-07:00',
    season: '春季',
    hiddenStems: ['乙']
  },
  辰: {
    id: '辰',
    zhi: '辰',
    title: '泥雲龍法師',
    description: '神秘的土系龍族，掌控變化的神奇力量，藏干複雜多變',
    element: '土',
    yinYang: '陽',
    color: '#DAA520',
    position: 'strategist',
    archetypes: ['變化龍師', '神秘長老', '萬象之主'],
    buff: '變化多端，資源豐富，應對複雜局面',
    buffValue: 22,
    debuff: '內在矛盾，難以統一，心思過雜',
    debuffValue: -14,
    personality: ['神秘', '變化', '威嚴', '多面'],
    actionStyle: '變幻莫測，隨機應變',
    storyKeywords: ['變化', '神秘', '複雜', '資源'],
    scenarioTemplate: '{title}掌握多變策略，{buff}應對各種局面，但{debuff}致決策遲疑。',
    timePeriod: '07:00-09:00',
    season: '春季',
    hiddenStems: ['戊', '乙', '癸']
  },
  巳: {
    id: '巳',
    zhi: '巳',
    title: '蛇焰術士',
    description: '智慧的火系術士，擁有深邃的洞察力，蛻變與重生之力',
    element: '火',
    yinYang: '陰',
    color: '#DC143C',
    position: 'strategist',
    archetypes: ['智焰法師', '蛻變導師', '洞察祭司'],
    buff: '洞察先機，蛻變能力，智謀深沉',
    buffValue: 22,
    debuff: '過於陰沉，心機過重，難以信任',
    debuffValue: -14,
    personality: ['智慧', '深邃', '變通', '洞察'],
    actionStyle: '蟄伏待機，一擊必中',
    storyKeywords: ['智慧', '蛻變', '洞察', '重生'],
    scenarioTemplate: '{title}以深沉智謀佈局，{buff}洞悉敵情，然{debuff}令人難以親近。',
    timePeriod: '09:00-11:00',
    season: '夏季',
    hiddenStems: ['丙', '戊', '庚']
  },
  午: {
    id: '午',
    zhi: '午',
    title: '日鬃騎兵',
    description: '熱情的火系騎兵，奔馳如烈火般激情，士氣高昂的先鋒',
    element: '火',
    yinYang: '陽',
    color: '#FF0000',
    position: 'strategist',
    archetypes: ['烈焰騎將', '衝鋒統帥', '熱血先鋒'],
    buff: '士氣高昂，行動迅速，感染力強',
    buffValue: 24,
    debuff: '過於衝動，難以持久，容易燃盡',
    debuffValue: -16,
    personality: ['熱情', '奔放', '積極', '激昂'],
    actionStyle: '熱血衝鋒，勢如烈火',
    storyKeywords: ['熱情', '衝鋒', '激昂', '迅速'],
    scenarioTemplate: '{title}帶領騎兵熱血衝鋒，{buff}振奮全軍，然{debuff}需及時收韁。',
    timePeriod: '11:00-13:00',
    season: '夏季',
    hiddenStems: ['丁', '己']
  },
  未: {
    id: '未',
    zhi: '未',
    title: '牧角調和者',
    description: '溫和的土系牧者，以溫柔守護群體，調和各方矛盾',
    element: '土',
    yinYang: '陰',
    color: '#F4A460',
    position: 'strategist',
    archetypes: ['和平牧者', '調和長老', '溫羊守護'],
    buff: '調和人心，化解矛盾，團隊凝聚',
    buffValue: 18,
    debuff: '優柔寡斷，缺乏魄力，容易被利用',
    debuffValue: -10,
    personality: ['溫和', '包容', '犧牲', '調和'],
    actionStyle: '潤物無聲，以和為貴',
    storyKeywords: ['調和', '溫柔', '守護', '包容'],
    scenarioTemplate: '{title}以溫柔力量調和團隊，{buff}凝聚人心，但{debuff}或顯軟弱。',
    timePeriod: '13:00-15:00',
    season: '夏季',
    hiddenStems: ['己', '丁', '乙']
  },
  申: {
    id: '申',
    zhi: '申',
    title: '金杖靈猴戰士',
    description: '機靈的金系戰士，動作敏捷且富有創意，變通能力極強',
    element: '金',
    yinYang: '陽',
    color: '#FFD700',
    position: 'strategist',
    archetypes: ['靈猴軍師', '巧變將軍', '機智統帥'],
    buff: '機智靈活，創意無限，適應力強',
    buffValue: 22,
    debuff: '過於投機，難以專注，花招過多',
    debuffValue: -12,
    personality: ['機靈', '活潑', '創新', '敏捷'],
    actionStyle: '七十二變，隨機應變',
    storyKeywords: ['機智', '靈活', '創意', '變通'],
    scenarioTemplate: '{title}以機智謀略出奇制勝，{buff}令敵難以預測，然{debuff}或失穩重。',
    timePeriod: '15:00-17:00',
    season: '秋季',
    hiddenStems: ['庚', '壬', '戊']
  },
  酉: {
    id: '酉',
    zhi: '酉',
    title: '鳳羽判衡者',
    description: '精準的金系衛士，時刻保持警覺與秩序，追求完美的裁決者',
    element: '金',
    yinYang: '陰',
    color: '#FFA500',
    position: 'strategist',
    archetypes: ['精準判官', '完美衛士', '秩序守護'],
    buff: '精準判斷，秩序井然，追求完美',
    buffValue: 20,
    debuff: '過於挑剔，不知變通，嚴苛無情',
    debuffValue: -12,
    personality: ['精準', '警覺', '有序', '完美'],
    actionStyle: '精準出擊，一針見血',
    storyKeywords: ['精準', '秩序', '完美', '判斷'],
    scenarioTemplate: '{title}以精準眼光評判戰局，{buff}維持軍紀，但{debuff}或失人心。',
    timePeriod: '17:00-19:00',
    season: '秋季',
    hiddenStems: ['辛']
  },
  戌: {
    id: '戌',
    zhi: '戌',
    title: '烽火戰犬統領',
    description: '忠誠的土系統領，守護家園的勇敢戰士，絕不背叛',
    element: '土',
    yinYang: '陽',
    color: '#CD853F',
    position: 'strategist',
    archetypes: ['忠犬將軍', '守護統帥', '烽火司令'],
    buff: '忠誠守護，勇敢無畏，絕不退縮',
    buffValue: 22,
    debuff: '過於固執，聽不進勸，疑心重',
    debuffValue: -14,
    personality: ['忠誠', '勇敢', '守護', '堅定'],
    actionStyle: '死守陣地，絕不後退',
    storyKeywords: ['忠誠', '守護', '勇敢', '堅定'],
    scenarioTemplate: '{title}忠心耿耿守護軍團，{buff}穩固後方，然{debuff}或顯頑固。',
    timePeriod: '19:00-21:00',
    season: '秋季',
    hiddenStems: ['戊', '辛', '丁']
  },
  亥: {
    id: '亥',
    zhi: '亥',
    title: '潮典海豚智者',
    description: '智慧的水系智者，擁有深邃的理解力，溫和而富有靈性',
    element: '水',
    yinYang: '陰',
    color: '#4682B4',
    position: 'strategist',
    archetypes: ['深海智者', '潮汐先知', '靈性導師'],
    buff: '智慧深邃，靈性高，理解力強',
    buffValue: 20,
    debuff: '過於天真，不切實際，容易被騙',
    debuffValue: -10,
    personality: ['智慧', '純真', '理解', '靈性'],
    actionStyle: '洞察局勢，順應潮流',
    storyKeywords: ['智慧', '靈性', '理解', '深邃'],
    scenarioTemplate: '{title}以深邃智慧洞察全局，{buff}預見未來，但{debuff}或過於理想。',
    timePeriod: '21:00-23:00',
    season: '冬季',
    hiddenStems: ['壬', '甲']
  }
};

// ==================== 輔助函數 ====================

export function getGanCharacter(gan: string): GanCharacter | null {
  return GAN_CHARACTERS[gan] || null;
}

export function getZhiCharacter(zhi: string): ZhiCharacter | null {
  return ZHI_CHARACTERS[zhi] || null;
}

export function getElementColor(element: WuxingElement): string {
  const colors: Record<WuxingElement, string> = {
    木: '#228B22',
    火: '#FF4500',
    土: '#8B4513',
    金: '#FFD700',
    水: '#4169E1'
  };
  return colors[element];
}
